In [1]:
import numpy as np
from scipy.sparse import csr_matrix
import pandas as pd

In [2]:
import sklearn
print('The scikit-learn version is {}.'.format(sklearn.__version__))

The scikit-learn version is 0.17.1.


In [3]:
mpzfile = np.load('../l6/files/out_4.dat.npz')

In [4]:
mpzfile.files

['data', 'users', 'users_tokens']

In [5]:
TRAINING_SET_URL = "train.csv"
EXAMPLE_SET_URL = "test_submition.csv"
df_users_train = pd.read_csv(TRAINING_SET_URL, sep=",", header=0, names=["uid", "cat"])
df_users_ex = pd.read_csv(EXAMPLE_SET_URL, sep=",", header=0, names=["uid", "cls"])
df_users_ex['cls'] = None

In [6]:
df_users_train.head()

uid  cat
0   202388889    1
1  1392518336    0
2   361208576    1
3  1535215357    1
4  4396196375    1

In [7]:
features = mpzfile['data'].item()

In [8]:
features.shape

(11479, 1015479)

In [9]:
users = mpzfile['users']

In [10]:
train_users = df_users_train["uid"].values
ix = np.in1d(users, train_users).reshape(users.shape)
X = features[np.where(ix)]

In [11]:
X

<6933x1015479 sparse matrix of type '<type 'numpy.float64'>'
	with 6043685 stored elements in Compressed Sparse Row format>

In [12]:
Y = []
classes = df_users_train['cat'].values

In [13]:
for user in users:
    try:
        ind = list(train_users).index(user)
    except:
        print user
        continue
    Y.append(classes[ind])

783836768
3064065145
25568299
19238906
4187257341
1487570167
2537744534
125106411
16999854
17358504
35139443
2396367234
21122957
60837794
17350532
1403732101
111857815
2730222890
291879347
3065897231
212137230
20881065
512780757
830302556
227787605
2877215733
2247717487
21123098
2842950429
3462698472
2434527313
118193682
619468116
90002008
43001050
2388815400
2183764969
2731703780
259936381
396048824
321594453
2478841038
18382998
155132335
3431589891
19636058
3322658109
2612505888
184299933
50782880
1449726048
1839646165
1942733947
763435751937830912
3148789382
18732595
748669315486883840
513564726
208252062
739133063515365376
246415716
17108553
6703212
2810037368
14411190
1323112933
39647359
434676278
257225604
304861372
2247139207
572422260
2308969400
962789539
735603874417938434
131989934
315509582
58353613
1546974656
749686272579428353
193185941
15190857
17756195
602200375
88679386
1674744967
1071486607
3074190323
709093222341980160
1670734141
181182783
182616130
2149747160
3945825

In [14]:
len(Y)

6933

In [15]:
from sklearn import metrics
from sklearn import cross_validation as cvd

In [21]:
from sklearn.linear_model import Ridge

rr = Ridge(alpha=10)

scores = cvd.cross_val_score(rr, X, Y, cv=5, scoring='roc_auc')

scores

array([ 0.59565395,  0.6086456 ,  0.5739998 ,  0.6095013 ,  0.56172819])

In [22]:
scores.mean()

0.58990576853083787

In [19]:
from sklearn.linear_model import Ridge

rr = Ridge(alpha=1)

scores = cvd.cross_val_score(rr, X, Y, cv=5, scoring='roc_auc')

scores

array([ 0.59686413,  0.61057372,  0.5735134 ,  0.61044818,  0.5618277 ])

In [20]:
scores.mean()

0.59064542473098458

In [27]:
from sklearn.linear_model import SGDRegressor

sgd = SGDRegressor()

scores = cvd.cross_val_score(sgd, X, Y, cv=5, scoring='roc_auc')
scores

array([ 0.5159583 ,  0.48622748,  0.51490887,  0.51536232,  0.49081097])

In [28]:
scores.mean()

0.50465358816316819

In [23]:
from sklearn.linear_model import PassiveAggressiveRegressor

pa = PassiveAggressiveRegressor()

scores = cvd.cross_val_score(pa, X, Y, cv=5, scoring='roc_auc')
scores

array([ 0.59727896,  0.60485863,  0.57690143,  0.60991972,  0.58007869])

In [24]:
scores.mean()

0.59380748864774913

In [29]:
from sklearn.linear_model import PassiveAggressiveRegressor

pa = PassiveAggressiveRegressor(loss='squared_epsilon_insensitive')

scores = cvd.cross_val_score(pa, X, Y, cv=5, scoring='roc_auc')
scores

array([ 0.60011701,  0.60561337,  0.57268895,  0.6119421 ,  0.54933325])

In [30]:
scores.mean()

0.58793893786024831

In [25]:
from sklearn.linear_model import PassiveAggressiveRegressor

pa = PassiveAggressiveRegressor(n_iter=10)

scores = cvd.cross_val_score(pa, X, Y, cv=5, scoring='roc_auc')
scores

array([ 0.6001728 ,  0.60910257,  0.57326407,  0.61292772,  0.57839001])

In [26]:
scores.mean()

0.59477143381454423

In [31]:
from sklearn.linear_model import PassiveAggressiveRegressor

pa = PassiveAggressiveRegressor(n_iter=10, loss='squared_epsilon_insensitive')

scores = cvd.cross_val_score(pa, X, Y, cv=5, scoring='roc_auc')
scores

array([ 0.60276767,  0.61270822,  0.57456422,  0.61330895,  0.55659017])

In [32]:
scores.mean()

0.59198784520823744

In [48]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

scores = cvd.cross_val_score(lr, X, Y, cv=5, scoring='roc_auc')
scores

array([ 0.59080585,  0.61914369,  0.57081279,  0.61029379,  0.55651711])

In [49]:
scores.mean()

0.58951464536983511

In [36]:
class MyRegressor:
    pa = PassiveAggressiveRegressor()
    rr = Ridge()
    def fit(self, X, y):
        self.pa = self.pa.fit(X,y)
        self.rr = self.rr.fit(X,y)
    def predict(self, X):
        pa_labels = self.pa.predict(X)
        rr_labels = self.rr.predict(X)
        return np.array((pa_labels + rr_labels) / 2)

In [34]:
test_users = df_users_ex['uid'].values
indices = []
for user in test_users:
    try:
        ind = list(users).index(user)
    except:
        indices.append(None)
        continue
    indices.append(ind)

In [35]:
indices

[6919,
 6920,
 6921,
 6922,
 6923,
 6924,
 6925,
 6926,
 6927,
 6928,
 6929,
 6930,
 6931,
 6932,
 6933,
 6934,
 6935,
 6936,
 6937,
 6938,
 6939,
 6940,
 6941,
 6942,
 6943,
 6944,
 6945,
 6946,
 6947,
 6948,
 6949,
 6950,
 6951,
 6952,
 6953,
 6954,
 6955,
 6956,
 None,
 None,
 6957,
 6958,
 6959,
 6960,
 6961,
 None,
 6962,
 6963,
 6964,
 6965,
 6966,
 None,
 6967,
 6968,
 6969,
 6970,
 6971,
 6972,
 6973,
 6974,
 6975,
 6976,
 None,
 6977,
 6978,
 6979,
 6980,
 6981,
 6982,
 6983,
 6984,
 6985,
 6986,
 6987,
 6988,
 6989,
 6990,
 6991,
 6992,
 6993,
 6994,
 6995,
 6996,
 6997,
 6998,
 6999,
 7000,
 7001,
 7002,
 7003,
 7004,
 7005,
 7006,
 7007,
 7008,
 7009,
 7010,
 7011,
 7012,
 7013,
 7014,
 7015,
 7016,
 7017,
 None,
 7018,
 None,
 7019,
 7020,
 7021,
 7022,
 7023,
 7024,
 7025,
 7026,
 7027,
 7028,
 7029,
 7030,
 7031,
 7032,
 7033,
 7034,
 7035,
 7036,
 7037,
 7038,
 7039,
 7040,
 7041,
 7042,
 7043,
 7044,
 7045,
 7046,
 7047,
 7048,
 7049,
 7050,
 7051,
 7052,
 7053,
 7054,

In [36]:
test = features[[x for x in indices if x is not None]]

In [50]:
lr = lr.fit(X,Y)
labels = lr.predict(test)

In [51]:
cats = []
j = 0
for i in range(len(test_users)):
    if indices[i] is not None:
        cats.append(labels[j])
        j += 1
    else:
        cats.append(0.5)

In [52]:
len(cats)

4748

In [45]:
len(test_users)

4748

In [53]:
df_users_ex = df_users_ex.assign(cls=cats)
df_users_ex.head()

uid  cls
0   783836768  1.0
1  3064065145  1.0
2    25568299  1.0
3    19238906  1.0
4  4187257341  1.0

In [54]:
df_users_ex.to_csv('./subm_LR_no_filter.csv', index=False)